### ISSUE TITLE
exception in console.

### ISSUE THREAD

**Issue by heroboy** [hoovercj/vscode-power-mode#51]
```
ERR Cannot read property 'selection' of undefined: TypeError: Cannot read property 'selection' of undefined
	at CursorExploder.constructor.explode (C:\Users\heroboy\.vscode\extensions\hoovercj.vscode-power-mode-2.2.0\out\src\cursor-exploder\cursor-exploder.js:145:67)
	at CursorExploder.constructor.onDidChangeTextDocument (C:\Users\heroboy\.vscode\extensions\hoovercj.vscode-power-mode-2.2.0\out\src\cursor-exploder\cursor-exploder.js:41:18)
	at plugins.forEach.plugin (C:\Users\heroboy\.vscode\extensions\hoovercj.vscode-power-mode-2.2.0\out\src\extension.js:119:38)
	at Array.forEach (<anonymous>)
	at onDidChangeTextDocument (C:\Users\heroboy\.vscode\extensions\hoovercj.vscode-power-mode-2.2.0\out\src\extension.js:119:13)
```

**Comment by hoovercj** [comment]
Thanks for reporting this! I believe I fixed anything that could have caused this in the just-shipped v3.0
